DROP TABLE IF EXISTS CATEGORIES;
 
CREATE TABLE CATEGORIES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  category_name VARCHAR(250) NOT NULL,
  category_description VARCHAR(250) NOT NULL,
  category_designator VARCHAR(250) DEFAULT NULL
);