DROP TABLE IF EXISTS CATEGORIES;
 
CREATE TABLE CATEGORIES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  category_name VARCHAR(250) NOT NULL,
  category_description VARCHAR(250) NOT NULL,
  category_designator VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS SUBCATEGORIES;

CREATE TABLE SUBCATEGORIES (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    subcategory_topic VARCHAR(250) NOT NULL,
    subcategory_description VARCHAR(250) NOT NULL,
    category_id INT,
    FOREIGN KEY (category_id) REFERENCES CATEGORIES(id)
);


DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    book_title VARCHAR(250) NOT NULL,
    book_isbn VARCHAR(250) NOT NULL,
    book_description VARCHAR(250) NOT NULL,
    book_price NUMERIC(5,2) NOT NULL,
    subcategory_id INT,
    FOREIGN KEY (subcategory_id) REFERENCES SUBCATEGORIES(id)
);

DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE AUTHORS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    author_name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS AUTHORS_BOOKS;

CREATE TABLE AUTHORS_BOOKS (
    authors_id INT, 
    books_id INT,
    FOREIGN KEY (authors_id) REFERENCES AUTHORS(id),
    FOREIGN KEY (books_id) REFERENCES BOOKS(id)
);

DROP TABLE IF EXISTS CARTS;

CREATE TABLE CARTS (
    id INT AUTO_INCREMENT  PRIMARY KEY
);


DROP TABLE IF EXISTS ITEMS;

CREATE TABLE ITEMS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    item_quantity INT, 
    book_id INT,
    cart_id INT,
    FOREIGN KEY (book_id) REFERENCES BOOKS(id),
    FOREIGN KEY (cart_id) REFERENCES CARTS(id)
);
